# Generated by Django 3.1 on 2020-08-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='boast',
            new_name='boast_roast',
        ),
    ]
